const asyncNames = {
  alfaIsTrueMulti: "alfaIsTrueMulti",
  alfaIsTrueMultiMixed: "alfaIsTrueMultiMixed",
  betaIsTrueMulti: "betaIsTrueMulti",
  betaIsTrueMultiMixed: "betaIsTrueMultiMixed",
  categoriesFilters: "categoriesFilters",
  createdQuestionsMultiFour: "createdQuestionsMultiFour",
  createdQuestionsMultiOne: "createdQuestionsMultiOne",
  createdQuestionsMultiThree: "createdQuestionsMultiThree",
  createdQuestionsMultiTwo: "createdQuestionsMultiTwo",
  createdQuestionsTrueFalseFour: "createdQuestionsTrueFalseFour",
  createdQuestionsTrueFalseOne: "createdQuestionsTrueFalseOne",
  createdQuestionsTrueFalseThree: "createdQuestionsTrueFalseThree",
  createdQuestionsTrueFalseTwo: "createdQuestionsTrueFalseTwo",
  deltaIsTrueMulti: "deltaIsTrueMulti",
  deltaIsTrueMultiMixed: "deltaIsTrueMultiMixed",
  gammaIsTrueMulti: "gammaIsTrueMulti",
  gammaIsTrueMultiMixed: "gammaIsTrueMultiMixed",
  indexTrueFalse: "indexTrueFalse",
  indexTrueFalseMixed: "indexTrueFalseMixed",
  indexTrueFalseNoTimer: "indexTrueFalseNoTimer",
  lastQuestionMinutesMulti: "lastQuestionMinutesMulti",
  lastQuestionMinutesMultiMixed: "lastQuestionMinutesMultiMixed",
  lastQuestionMinutesTrueFalse: "lastQuestionMinutesTrueFalse",
  lastQuestionMinutesTrueFalseMixed: "lastQuestionMinutesTrueFalseMixed",
  lastQuestionSecondsMulti: "lastQuestionSecondsMulti",
  lastQuestionSecondsMultiMixed: "lastQuestionSecondsMultiMixed",
  lastQuestionSecondsTrueFalse: "lastQuestionSecondsTrueFalse",
  lastQuestionSecondsTrueFalseMixed: "lastQuestionSecondsTrueFalseMixed",
  localDataBaseMultiFour: "localDataBaseMultiFour",
  localDataBaseMultiMixedFour: "localDataBaseMultiMixedFour",
  localDataBaseMultiMixedOne: "localDataBaseMultiMixedOne",
  localDataBaseMultiMixedThree: "localDataBaseMultiMixedThree",
  localDataBaseMultiMixedTwo: "localDataBaseMultiMixedTwo",
  localDataBaseMultiOne: "localDataBaseMultiOne",
  localDataBaseMultiThree: "localDataBaseMultiThree",
  localDataBaseMultiTwo: "localDataBaseMultiTwo",
  localDatabaseTrueFalseFour: "localDatabaseTrueFalseFour",
  localDatabaseTrueFalseMixedFour: "localDatabaseTrueFalseMixedFour",
  localDatabaseTrueFalseMixedOne: "localDatabaseTrueFalseMixedOne",
  localDatabaseTrueFalseMixedThree: "localDatabaseTrueFalseMixedThree",
  localDatabaseTrueFalseMixedTwo: "localDatabaseTrueFalseMixedTwo",
  localDatabaseTrueFalseOne: "localDatabaseTrueFalseOne",
  localDatabaseTrueFalseThree: "localDatabaseTrueFalseThree",
  localDatabaseTrueFalseTwo: "localDatabaseTrueFalseTwo",
  min: "min",
  mixedQuestionsAreOnTrueFalse: "mixedQuestionsAreOnTrueFalse",
  mixGameIsOnMulti: "mixGameIsOnMulti",
  mixGameIsOnMultiNoTimer: "mixGameIsOnMultiNoTimer",
  mixGameIsOnTrueFalse: "mixGameIsOnTrueFalse",
  mixGameIsOnTrueFalseNoTimer: "mixGameIsOnTrueFalseNoTimer",
  noIsChosen: "noIsChosen",
  numOfRemainQuestionsTrueFalseFour: "numOfRemainQuestionsTrueFalseFour",
  numOfRemainQuestionsTrueFalseFourNoTimer:
    "numOfRemainQuestionsTrueFalseFourNoTimer",
  numOfRemainQuestionsTrueFalseMixed: "numOfRemainQuestionsTrueFalseMixed",
  numOfRemainQuestionsTrueFalseOne: "numOfRemainQuestionsTrueFalseOne",
  numOfRemainQuestionsTrueFalseOneNoTimer:
    "numOfRemainQuestionsTrueFalseOneNoTimer",
  numOfRemainQuestionsTrueFalseThree: "numOfRemainQuestionsTrueFalseThree",
  numOfRemainQuestionsTrueFalseThreeNoTimer:
    "numOfRemainQuestionsTrueFalseThreeNoTimer",
  numOfRemainQuestionsTrueFalseTwo: "numOfRemainQuestionsTrueFalseTwo",
  numOfRemainQuestionsTrueFalseTwoNoTimer:
    "numOfRemainQuestionsTrueFalseTwoNoTimer",
  numOfTotQuestionsMultiFour: "numOfTotQuestionsMultiFour",
  numOfTotQuestionsMultiFourNoTimer: "numOfTotQuestionsMultiFourNoTimer",
  numOfTotQuestionsMultiMixed: "numOfTotQuestionsMultiMixed",
  numOfTotQuestionsMultiOne: "numOfTotQuestionsMultiOne",
  numOfTotQuestionsMultiOneNoTimer: "numOfTotQuestionsMultiOneNoTimer",
  numOfTotQuestionsMultiThree: "numOfTotQuestionsMultiThree",
  numOfTotQuestionsMultiThreeNoTimer: "numOfTotQuestionsMultiThreeNoTimer",
  numOfTotQuestionsMultiTwo: "numOfTotQuestionsMultiTwo",
  numOfTotQuestionsMultiTwoNoTimer: "numOfTotQuestionsMultiTwoNoTimer",
  numOfTotQuestionsTrueFalseFour: "numOfTotQuestionsTrueFalseFour",
  numOfTotQuestionsTrueFalseFourNoTimer:
    "numOfTotQuestionsTrueFalseFourNoTimer",
  numOfTotQuestionsTrueFalseMixed: "numOfTotQuestionsTrueFalseMixed",
  numOfTotQuestionsTrueFalseOne: "numOfTotQuestionsTrueFalseOne",
  numOfTotQuestionsTrueFalseOneNoTimer: "numOfTotQuestionsTrueFalseOneNoTimer",
  numOfTotQuestionsTrueFalseThree: "numOfTotQuestionsTrueFalseThree",
  numOfTotQuestionsTrueFalseThreeNoTimer:
    "numOfTotQuestionsTrueFalseThreeNoTimer",
  numOfTotQuestionsTrueFalseTwo: "numOfTotQuestionsTrueFalseTwo",
  numOfTotQuestionsTrueFalseTwoNoTimer: "numOfTotQuestionsTrueFalseTwoNoTimer",
  questionsMultiFour: "questionsMultiFour",
  questionsMultiFourNoTimer: "questionsMultiFourNoTimer",
  questionsMultiMixed: "questionsMultiMixed",
  questionsMultiOne: "questionsMultiOne",
  questionsMultiOneNoTimer: "questionsMultiOneNoTimer",
  questionsMultiThree: "questionsMultiThree",
  questionsMultiThreeNoTimer: "questionsMultiThreeNoTimer",
  questionsMultiTwo: "questionsMultiTwo",
  questionsMultiTwoNoTimer: "questionsMultiTwoNoTimer",
  questionsRightChoices: "questionsRightChoices",
  questionsRightChoicesNoTimer: "questionsRightChoicesNoTimer",
  questionsTrueFalseFour: "questions_TrueFalseFour",
  questionsTrueFalseFourNoTimer: "questionsTrueFalseFourNoTimer",
  questionsTrueFalseMixed: "questionsTrueFalseMixed",
  questionsTrueFalseOne: "questionsTrueFalseOne",
  questionsTrueFalseOneNoTimer: "questionsTrueFalseOneNoTimer",
  questionsTrueFalseThree: "questionsTrueFalseThree",
  questionsTrueFalseThreeNoTimer: "questionsTrueFalseThreeNoTimer",
  questionsTrueFalseTwo: "questionsTrueFalseTwo",
  questionsTrueFalseTwoNoTimer: "questionsTrueFalseTwoNoTimer",
  refreshToken: "refreshToken",
  savedPoints: "savedPoints",
  sec: "sec",
  skipIntroScreen: "skipIntroScreen",
  totalPointsMultiFour: "totalPointsMultiFour",
  totalPointsMultiFourNoTimer: "totalPointsMultiFourNoTimer",
  totalPointsMultiMixed: "totalPointsMultiMixed",
  totalPointsMultiOne: "totalPointsMultiOne",
  totalPointsMultiOneNoTimer: "totalPointsMultiOneNoTimer",
  totalPointsMultiThree: "totalPointsMultiThree",
  totalPointsMultiThreeNoTimer: "totalPointsMultiThreeNoTimer",
  totalPointsMultiTwo: "totalPointsMultiTwo",
  totalPointsMultiTwoNoTimer: "totalPointsMultiTwoNoTimer",
  totalPointsTrueFalseFour: "totalPointsTrueFalseFour",
  totalPointsTrueFalseFourNoTimer: "totalPointsTrueFalseFourNoTimer",
  totalPointsTrueFalseMixed: "totalPointsTrueFalseMixed",
  totalPointsTrueFalseOne: "totalPointsTrueFalseOne",
  totalPointsTrueFalseOneNoTimer: "totalPointsTrueFalseOneNoTimer",
  totalPointsTrueFalseThree: "totalPointsTrueFalseThree",
  totalPointsTrueFalseThreeNoTimer: "totalPointsTrueFalseThreeNoTimer",
  totalPointsTrueFalseTwo: "totalPointsTrueFalseTwo",
  totalPointsTrueFalseTwoNoTimer: "totalPointsTrueFalseTwoNoTimer",
  totalTimeLeftMultiFour: "totalTimeLeftMultiFour",
  // totalTimeLeftMultiMixed: "totalTimeLeftMultiMixed",
  totalTimeLeftMultiOne: "totalTimeLeftMultiOne",
  totalTimeLeftMultiThree: "totalTimeLeftMultiThree",
  totalTimeLeftMultiTwo: "totalTimeLeftMultiTwo",
  totalTimeLeftTrueFalseFour: "totalTimeLeftTrueFalseFour",
  totalTimeLeftTrueFalseMixed: "totalTimeLeftTrueFalseMixed",
  totalTimeLeftTrueFalseOne: "totalTimeLeftTrueFalseOne",
  totalTimeLeftTrueFalseThree: "totalTimeLeftTrueFalseThree",
  totalTimeLeftTrueFalseTwo: "totalTimeLeftTrueFalseTwo",
  userData: "userData",
  userName: "userName",
  useTimerMultiMixed: "useTimerMultiMixed",
  useTimerTrueFalseMixed: "useTimerTrueFalseMixed",
  yesIsChosen: "yesIsChosen",
};

export default asyncNames;