const navNames = {
  auth: "Auth",
  createMultiCategories: "CreateMultiCategories",
  createNavigator: "CreateNavigator",
  createMultiOverview: "CreateMultiOverview",
  createTrueFalse: "CreateTrueFalse",
  createTrueFalseCategories: "CreateTrueFalseCategories",
  createTrueFalseOverview: "CreateTrueFalseOverview",
  createWelcome: "CreateWelcome",
  editMultiQuestion: "EditMultiQuestion",
  editTrueFalseQuestion: "EditTrueFalseQuestion",
  forgotPassword: "ForgotPassword",
  gameInfo: "GameInfo",
  gameInfoNavigator: "GameInfoNavigator",
  gameNavigator: "GameNavigator",
  intro: "Intro",
  mixedChooseCategories: "MixedChooseCategories",
  noTimerMixedGame: "NoTimerMixedGame",
  mixedMultiGame: "MixedMultiGame",
  mixedTrueFalseGame: "MixedTrueFalseGame",
  multiCategories: "MultiCategories",
  multiGame: "MultiGame",
  noTimerMultiCategories: "NoTimerMultiCategories",
  noTimerMultiGame: "NoTimerMultiGame",
  noTimerTrueFalseCategories: "NoTimerTrueFalseCategories",
  noTimerTrueFalseMixedGame: "NoTimerTrueFalseMixedGame",
  noTimerTrueFalseGame: "NoTimerTrueFalseGame",
  settings: "Settings",
  settingsNavigator: "SettingsNavigator",
  trueFalseCategories: "TrueFalseCategories",
  trueFalseGame: "TrueFalseGame",
  welcome: "Welcome",
  winners: "Winners",
  winnersNavigator: "WinnersNavigator",
};

export default navNames;