
const navNames = {
  winners: "winners",
  settings: "settings",
  create: "create",
  auth: 'auth',
  donate: 'donate',
  not_found: 'not-found',
  createMultiCategories: "CreateMultiCategories",
  createNavigator: "CreateNavigator",
  createMultiOverview: "CreateMultiOverview",
  createTrueFalse: "CreateTrueFalse",
  createTrueFalseCategories: "CreateTrueFalseCategories",
  createTrueFalseOverview: "CreateTrueFalseOverview",
  editMultiQuestion: "EditMultiQuestion",
  editTrueFalseQuestion: "EditTrueFalseQuestion",
  forgotPassword: "ForgotPassword",
  gameInfo: "GameInfo",
  gameInfoNavigator: "GameInfoNavigator",
  gameNavigator: "GameNavigator",
  intro: "Intro",
  mixedChooseCategories: "MixedChooseCategories",
  noTimerMixedGame: "NoTimerMixedGame",
  mixedMultiGame: "MixedMultiGame",
  mixedTrueFalseGame: "MixedTrueFalseGame",
  multiCategories: "MultiCategories",
  multiGame: "MultiGame",
  noTimerMultiCategories: "NoTimerMultiCategories",
  noTimerMultiGame: "NoTimerMultiGame",
  noTimerTrueFalseCategories: "NoTimerTrueFalseCategories",
  noTimerTrueFalseMixedGame: "NoTimerTrueFalseMixedGame",
  noTimerTrueFalseGame: "NoTimerTrueFalseGame",

  settingsNavigator: "SettingsNavigator",
  trueFalseCategories: "TrueFalseCategories",
  trueFalseGame: "TrueFalseGame",
  welcome: "Welcome",
  winnersNavigator: "WinnersNavigator",
};

export default navNames;